[package]
name = "layout-hillclimber"
version = "0.0.0"
authors = ["ashtneoi <ashtneoi@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
num-format = "0.4.0"
rand = "0.8.3"
signal-hook = "0.3.6"
